config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :users, only: [:show] # ユーザーマイページへのルーティング
  resources :composers
  # root "posts#index"
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  root 'tweets#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/composer.rb
class Composer < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記
  has_many :comments, dependent: :destroy
  has_one_attached :image 

  mount_uploader :image, ImageUploader

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # deviseコントローラーにストロングパラメータを追加する          
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/composers_controller.rb
class ComposersController < ApplicationController
    def index

    end


    def new
    @composer = Composer.new
    end

    def create
        @composer = Composer.new(composer_params)
        answers = [
            @composer.question1,
            @composer.question2,
            @composer.question3,
            @composer.question4,
            @composer.question5,
            @composer.question6,
            @composer.question7,
        ]
        @composer.a_count = answers.count { |a| a == "2" }
        if @composer.save
            flash[:notice] = "診断が完了しました"
            redirect_to @composer and return
        else
            redirect_to :action => "new"
        end
    end


    def show
        @composer = Composer.find(params[:id])
    end

    private

    def composer_params
    params.require(:composer).permit(
        :question1, :question2, :question3, :question4,
        :question5, :question6, :question7, :a_count
    )
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

#追加箇所
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @tweets = Tweet.all
    all_tweets = Tweet.includes(:user).order(created_at: :desc)
    @top_liked_tweets = all_tweets.sort_by { |t| -t.likes.count }.first(6)
    @recent_tweets = all_tweets.reject { |t| @top_liked_tweets.include?(t) }
  end

  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)

    tweet.user_id = current_user.id

    if tweet.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])

    @comments = @tweet.comments
    @comment = Comment.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:title, :about, :genre, :video, :twitter_url, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/composers_helper.rb
module ComposersHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def find_youtube_url(video)
    return nil if video.nil?

    if video[0..16] == "https://youtu.be/"
      return video[17..27]
      # "https://youtu.be/WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
    else
      return video[32..42]
      # "https://www.youtube.com/watch?v=WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
    end
  end

  def find_tweet_id(twitter_url)
   regex = /(twitter\.com|x\.com)\/\w+\/status\/(\d+)/
   match = twitter_url.match(regex)
   match[2] if match
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/composers/index.html.erb
<div class="startdiag">
  <br>
  <div class="diagintro1">
    <div class="diagtext">
      <h1>作曲家性格診断</h1>
      あなたの性格に合った作曲家や曲を見つけるための診断を始めましょう。
      <br><br><br>
      <h2>あなたにぴったりの作曲家を見つけよう</h2>
      この診断では、あなたの性格に最も合った作曲家とその代表曲を見つけることができます。質問に答えるだけで、オーケストラ音楽の新たな楽しみ方を発見しましょう。
    </div>
    <div class="diagimage">
      <img src="/assets/comp/cmp.jpg" alt="作曲家診断イメージ">
    </div>
  </div>
  <br>
  <div class="diagbutton">
    <%= link_to "作曲家診断スタート", new_composer_path, class: "btnlink" %>
  </div>
</div>

app/views/composers/new.html.erb
<%= form_for(@composer, class: 'composer-form', role: 'form') do |f| %>
  <div class="composer-container">
    <div class="composer-question-group">
      <div class="composer-question">
        <p>Q1. 自分はどちらかと言うと…</p>
      </div>
      <div class="composer-options">
        <%= f.radio_button :question1, "1", id: "q1_option1", class: "composer-radio" %>
        <label for="q1_option1" class="composer-label">感情豊かで情熱的</label>
        <%= f.radio_button :question1, "2", id: "q1_option2", class: "composer-radio" %>
        <label for="q1_option2" class="composer-label">冷静で論理的</label>
      </div>
    </div>
    
    <div class="composer-question-group">
      <div class="composer-question">
        <p>Q2. 音楽で大事なのは?</p>
      </div>
      <div class="composer-options">
        <%= f.radio_button :question2, "1", id: "q2_option1", class: "composer-radio" %>
        <label for="q2_option1" class="composer-label">感動や物語性</label>
        <%= f.radio_button :question2, "2", id: "q2_option2", class: "composer-radio" %>
        <label for="q2_option2" class="composer-label">技術や構造美</label>
      </div>
    </div>
    
    <div class="composer-question-group">
      <div class="composer-question">
        <p>Q3. 作業スタイルは?</p>
      </div>
      <div class="composer-options">
        <%= f.radio_button :question3, "1", id: "q3_option1", class: "composer-radio" %>
        <label for="q3_option1" class="composer-label">ひらめきや気分を重視する</label>
        <%= f.radio_button :question3, "2", id: "q3_option2", class: "composer-radio" %>
        <label for="q3_option2" class="composer-label">計画的・論理的に進める</label>
      </div>
    </div>
    
    <div class="composer-question-group">
      <div class="composer-question">
        <p>Q4. 理想の演奏スタイルは?</p>
      </div>
      <div class="composer-options">
        <%= f.radio_button :question4, "1", id: "q4_option1", class: "composer-radio" %>
        <label for="q4_option1" class="composer-label">豪快でエモーショナル</label>
        <%= f.radio_button :question4, "2", id: "q4_option2", class: "composer-radio" %>
        <label for="q4_option2" class="composer-label">精密で繊細</label>
      </div>
    </div>
    
    <div class="composer-question-group">
      <div class="composer-question">
        <p>Q5. 人生観として近いのは?</p>
      </div>
      <div class="composer-options">
        <%= f.radio_button :question5, "1", id: "q5_option1", class: "composer-radio" %>
        <label for="q5_option1" class="composer-label">ドラマチックに行きたい</label>
        <%= f.radio_button :question5, "2", id: "q5_option2", class: "composer-radio" %>
        <label for="q5_option2" class="composer-label">落ち着いた人生を送りたい</label>
      </div>
    </div>
    
    <div class="composer-question-group">
      <div class="composer-question">
        <p>Q6. 歴史や伝統に対して</p>
      </div>
      <div class="composer-options">
        <%= f.radio_button :question6, "1", id: "q6_option1", class: "composer-radio" %>
        <label for="q6_option1" class="composer-label">壊して新しくしたい</label>
        <%= f.radio_button :question6, "2", id: "q6_option2", class: "composer-radio" %>
        <label for="q6_option2" class="composer-label">尊重しながら発展させたい</label>
      </div>
    </div>
    
    <div class="composer-question-group">
      <div class="composer-question">
        <p>Q7. どちらの環境が落ち着く?</p>
      </div>
      <div class="composer-options">
        <%= f.radio_button :question7, "1", id: "q7_option1", class: "composer-radio" %>
        <label for="q7_option1" class="composer-label">自然や外の世界</label>
        <%= f.radio_button :question7, "2", id: "q7_option2", class: "composer-radio" %>
        <label for="q7_option2" class="composer-label">静かな部屋で一人の時間</label>
      </div>
    </div>
    
    <div class="composer-submit-btn">
      <%= f.submit "結果", class: "composer-result-btn" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Orch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/ed777ebbd4.js"  crossorigin="anonymous"></script> 

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>
  <header>
    <img src="assets/ov_logo.png" width="70" height="70" alt="">
    <h1>Orchestra Vlog</h1>
    <div class="header-list">
    <ul>
      <li><%= link_to "作曲家性格診断",composers_path, class: "buttonUnderline" %></li>
      <li><%= link_to "新規投稿",new_tweet_path, class: "buttonUnderline" %></li>
      <% if user_signed_in? %>
      <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: "buttonUnderline" %></li>
      <% else %>
      <li><%= link_to "新規登録", new_user_registration_path, class: "buttonUnderline" %></li>
      <li><%= link_to "ログイン", new_user_session_path, class: "buttonUnderline" %></li>
      <% end %>
      <li><%= link_to "ホーム", tweets_path, class: "buttonUnderline" %></li>
      </ul>
    </div>
  </header>
  <main>
    <%= yield %>
  </main>
  <footer>
    <p>Copyright © GeekSalon All Rights Reserved.</p>
  </footer>
  </body>
  


</html>

app/views/tweets/edit.html.erb
<div class="post-container">
  <%= form_for @tweet do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, :size => 30 %>
    <br>
    <%= f.label :titleimage %>
    <%= f.file_field :image, :size => 30 %>
    <br>
    <%= f.label :genre %>
    <%= f.text_field :genre, :size => 30 %>
    <br>
    <%= f.label :about %>
    <br>
    <%= f.text_area :about, :size => "65x10" %>
    <br>
    <br>
    <%= f.label :video %>
    <%= f.text_field :video, :size => 140 %>
    <br>
    <%= f.label :twitter_url %>
    <%= f.text_field :twitter_url, size: 140 %>
    <br>
    <%= f.submit "編集を保存する" %>
  <% end %>
</div>

app/views/tweets/index.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=M+PLUS+2:wght@100..900&display=swap" rel="stylesheet">
<!-- Splide CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.3/dist/css/splide.min.css">
<!-- Splide JS -->
<script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.3/dist/js/splide.min.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    new Splide('#image-carousel', {
      type: 'loop',           // ループさせる
      autoplay: true,         // 自動再生
      interval: 3000,         // 3秒ごとに切り替え
      pauseOnHover: false,    // ホバーしても止めない
      arrows: false,          // 矢印を非表示
      pagination: false,      // ページネーションを非表示
    }).mount();
  });
</script>


<div class="image">
  <div id="image-carousel" class="splide">
    <div class="splide__track">
      <ul class="splide__list">
        <li class="splide__slide"><img src="assets/swiss.jpg" alt=""></li>
      </ul>
    </div>
  </div>
  <p>あなたの知らない<br>オーケストラの世界へ。</p>
</div>

<div class="sechead">
  <div class ="sentence1">
    多様な仲間と共に♬
  </div>
  <div class = "sentence2">
    オーケストラは、音楽を通じて人々を結びつける力があります。言葉を超えたコミュニケーションが可能です。
    <br>
    また、世界にはいくつものオーケストラ団体が存在し、それぞれが唯一無二の魅力を持っています。
  </div>
  <div class="slideshow">
  <img class="slideimage" src="assets/gali.jpg" alt="">
  <img class="slideimage" src="assets/core.jpg" alt="">
  <img class="slideimage" src="assets/pio.jpg" alt="">
  <img class="slideimage" src="assets/sch.jpg" alt="">
  <img class="slideimage" src="assets/sch1.jpg" alt="">
  </div>
</div>

<div class="intro">
  <div class = "intro-sen1">
    投稿一覧
  </div>
  <div class = "intro-sen2">
    オーケストラは多様な楽器が集まり、豊かな音楽を生み出します。各セクションが調和し、感動的な演奏を実現します。より詳しく知るには、以下からどうぞ。
  </div>

</div>

<div class="ninki">
  <h2>人気の投稿（いいね順）</h2>
</div>
<div class="tweets-container">
  <% @top_liked_tweets.each do |t| %>
    <div class="tweet">
      <div class="main-box">
        <div class="left-container">
          <%= link_to t.title, tweet_path(t.id), class: "t-title" %>
    
          <div class="user-info">
            <div class="t-image">
              <%= image_tag t.user.image_url, size: "24x24" if t.user.image? %>
            </div>
            <%= link_to t.user.name, user_path(t.user_id), class: "t-name" %>
          </div>
    
          <br>
          <%= t.genre %>
          <% about_text = t.about.to_s %>
          <%= simple_format((t.video.blank? && t.twitter_url.blank?) ? (about_text.length > 150 ? "#{about_text[0...150]}..." : about_text) : (about_text.length > 40 ? "#{about_text[0...40]}..." : about_text)) %>
        </div>

        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% end %>
        <% else %>
          <i class="fas fa-heart"></i><%= t.likes.count %>
        <% end %>
      </div>

      <div class="titleimage">
        <% if t.image.present? %>
          <%= image_tag t.image_url, size: "500x400" if t.image? %>
        <% else %>
          <p> </p>
        <% end %>
      </div>

      <div class="right-container">
        <% if user_signed_in? && current_user.id == t.user_id %>
          <%= link_to "編集する", edit_tweet_path(t.id), class: "btnlink" %>
          <%= link_to "削除する", tweet_path(t.id), method: :delete, class: "btnlink" %>
        <% end %>
      </div>

      <p class="time"><%= t.created_at.strftime("%Y年%m月%d日 %H:%M") %></p>
    </div>
  <% end %>
</div>

<div class="ninki">
  <h2>新着投稿</h2>
</div>
  <div class="tweets-container">
  <% @recent_tweets.each do |t| %>
    <div class="tweet">
      <div class="main-box">
        <div class="left-container">
          <%= link_to t.title, tweet_path(t.id), class: "t-title" %>
          <div class="t-image">
            <%= image_tag t.user.image_url, size: "25x25" if t.user.image? %>
          </div>
          <%= link_to t.user.name, user_path(t.user_id), class: "t-name" %>
          <br>
          <%= t.genre %>
          <% about_text = t.about.to_s %>
          <%= simple_format((t.video.blank? && t.twitter_url.blank?) ? (about_text.length > 150 ? "#{about_text[0...150]}..." : about_text) : (about_text.length > 40 ? "#{about_text[0...40]}..." : about_text)) %>
        </div>

        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= button_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= button_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% end %>
        <% else %>
          <i class="fas fa-heart"></i><%= t.likes.count %>
        <% end %>
      </div>

      <div class="titleimage">
        <% if t.image.present? %>
          <%= image_tag t.image_url, size: "500x400" if t.image? %>
        <% else %>
          <p> </p>
        <% end %>
      </div>

      <div class="right-container">
        <% if user_signed_in? && current_user.id == t.user_id %>
          <%= link_to "編集する", edit_tweet_path(t.id), class: "btnlink" %>
          <%= link_to "削除する", tweet_path(t.id), method: :delete, class: "btnlink" %>
        <% end %>
      </div>

      <p class="time"><%= t.created_at.strftime("%Y年%m月%d日 %H:%M") %></p>
    </div>
  <% end %>
</div>
<div class="image2">
  <img src="/assets/concert.jpg" alt="">
  <p>Schnitzel Philharmonic Orchestra</p>
</div>
<div class = "sch">
  <div class = "sch-1">
    オーケストラの魅力を<br>お届けします
  </div>
  <br>
  <div class = "sch-2">
    オーケストラの最新情報やイベントをお楽しみください
    <br>
    シュニッツェルフィルハーモニー管弦楽団
    <br>
    <a href="https://schnitzelphil.com/" target="_blank">
    Schnitzel Philharmonic Orchestra 公式サイト
    </a>
  </div>
  <br>
  <div class = "sch-3">
    <img src="/assets/logo.png" alt="">
  </div>
</div>

app/views/tweets/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="post-container">
    <p class="title">投稿フォーム</p>
    オーケストラにまつわる記事を投稿することで、<br>楽しさを共有しましょう。
    <%= form_for(@tweet, :url => { controller:'tweets', action:'create'})do |f| %>
    <br>
    <%= f.label :title %>
    <%= f.text_field :title, :size => 30 %>
    <br>
    <%= f.label :titleimage %>
    <%= f.file_field :image, :size => 30 %>
    <br>
    <%= f.label :genre %>
    <%= f.text_field :genre, :size => 30 %>
    <br>
    <%= f.label :about %>
    <br>
    <%= f.text_area :about, :size => "65x10" %>
    <br>
    <br>
    <%= f.label :video %>
    <%= f.text_field :video, :size => 140 %>
    <br>
    <%= f.label :twitter_url %>
    <%= f.text_field :twitter_url, size: 140 %>
    <br>
    <div class="actions">
        <%= f.submit "送信"%>
    <br>
    </div>
    <% end %>
    <%= link_to "一覧に戻る", tweets_path %>
</div>

app/views/tweets/show.html.erb
<h3>ブログ詳細</h3>
<class="tweet">
  <div class="show-head">
  <div class="splide">
    <div class="splide__track">
      <ul class="splide__list">
        <li class="splide__slide2">
          <img src="<%= @tweet.image %>" alt="">
        </li>
      </ul>
    </div>
  </div>
  <p class="centered-text"><%= @tweet.title %></p>
</div>
  <div class="vlogbody">
    <p> #<%= @tweet.genre %></p>
    <br>
    <p><%= simple_format(@tweet.about.to_s) %></p>
    <br>
    <% if @tweet.video.present? %>
      <div class="youtube-container">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= find_youtube_url(@tweet.video) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    <% end %>
    <% if @tweet.twitter_url.present? %>
      <% tweet_id = find_tweet_id(@tweet.twitter_url) %>
      <blockquote class="twitter-tweet">
        <a href="https://twitter.com/i/status/<%= tweet_id %>"></a>
    </blockquote>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    <% else %>
      <p></p>
    <% end %>
    <br>
    <p><%= @tweet.created_at %></p>
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <% if current_user.already_liked?(@tweet) %>
        <%= button_to tweet_like_path(@tweet), method: :delete do %>
          <i class="fas fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
      <% else %>
        <%= button_to tweet_likes_path(@tweet), method: :post do %>
          <i class="fas fa-heart"></i><%= @tweet.likes.count %>
        <% end %>
      <% end %>
      <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
    <% else %>
      <i class="far fa-heart"></i><%= @tweet.likes.count %>
    <% end %>
    <br>
    <div class="iine">
      <h2>いいねしたユーザー</h2>
      <% @tweet.liked_users.each do |user| %>
      <li><%= user.name %></li>
    <% end %>
    </div>

    <div class="comment-wrapper">
      <p>コメント一覧</p>
      <% @comments.each do |c| %>
        <div>
          <%= c.user.name unless c.user.blank? %>
          <br>
          <%= c.content %>
        </div>
          <br>
      <% end %>

      <% if user_signed_in? %>
        <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
          <%= f.text_area :content %>
          <%= button_tag type: "submit" do %>
            <i class="far fa-comments"></i> コメントする
          <% end %>
        <% end %>
      <% end %>
      <%= link_to "ブログ一覧に戻る", tweets_path, class: "btnlink2" %>
    </div>
    
    </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="mypage-container">
  <div class="user-profile-card">
    <div class="profile-header">
      <h1 class="profile-title">My page</h1>
      <div class="profile-actions">
        <% if user_signed_in? && current_user.id == @user.id %>
          <%= link_to "編集する", edit_user_registration_path, class: "edit-profile-btn" %>
        <% end %>
      </div>
    </div>
    <div class="profile-details">
      <p class="user-name"><%= @user.name %></p>
      <%= image_tag @user.image_url, size: "50x50", class: "user-image" if @user.image? %>
      <p class="user-email">メールアドレス: <%= @user.email %></p>
      <p class="user-bio"><%= @user.profile %></p>
    </div>
  </div>

  <div class="user-posts-card">
    <h2 class="section-title">ユーザーの投稿一覧</h2>
    <ul class="post-list">
      <% @user.tweets.each do |t| %>
        <li class="post-item">
          <%= link_to t.title, tweet_path(t.id), class: "post-link" %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="user-likes-card">
    <h2 class="section-title">ユーザーがいいねした投稿一覧</h2>
    <ul class="liked-post-list">
      <% @user.liked_tweets.each do |t| %>
        <li class="liked-post-item">
          <div class="post-info">
            <% if t.user.image? %>
              <%= image_tag t.user.image_url, size: '25x25', class: "liked-user-image" %>
            <% end %>
            <span class="liked-user-name"><%= t.user.name %></span>
          </div>
          <%= link_to t.title, tweet_path(t.id), class: "liked-post-title" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<%= link_to "ブログ一覧に戻る", tweets_path, class: "back-link" %>